{"name": "For_Loop", "status": "failed", "statusDetails": {"message": "Failure occurred and exit-on-failure mode is in use."}, "start": 1666105276895, "stop": 1666105276895, "uuid": "d9512adb-07d0-40e6-bf96-26fb635cb6fa", "historyId": "da6986a968d758cb84e49d003f3fdd15", "fullName": "TestCases.Text.For_Loop", "labels": [{"name": "suite", "value": "TestCases"}, {"name": "subSuite", "value": "Text"}, {"name": "framework", "value": "robotframework"}, {"name": "language", "value": "cpython3"}, {"name": "host", "value": "MSDT081"}, {"name": "thread", "value": "default-5538b50a-eac0-4cc2-8db2-64e5dbdc92a8"}, {"name": "tag", "value": "robot:exit"}, {"name": "tag", "value": "robot:exit"}]}