{"name": "Deleting Customer from the website", "status": "failed", "statusDetails": {"message": "Failure occurred and exit-on-failure mode is in use."}, "description": "This Test case delete the new customer and verify that deleted or not.", "start": 1666105276873, "stop": 1666105276873, "uuid": "9d88fa76-ec32-4665-a082-baca2de2f710", "historyId": "eb91f8faf7548c22dfddb39f4b6178f4", "fullName": "TestCases.TestCase.Deleting Customer from the website", "labels": [{"name": "suite", "value": "TestCases"}, {"name": "subSuite", "value": "TestCase"}, {"name": "framework", "value": "robotframework"}, {"name": "language", "value": "cpython3"}, {"name": "host", "value": "MSDT081"}, {"name": "thread", "value": "default-5538b50a-eac0-4cc2-8db2-64e5dbdc92a8"}, {"name": "tag", "value": "Deleting Customer"}, {"name": "tag", "value": "robot:exit"}, {"name": "tag", "value": "Deleting Customer"}, {"name": "tag", "value": "robot:exit"}]}